theme: jekyll-theme-console
style: dark # dark (default) or light

locale: "en-US"
title: "PathologicalHandwaving"
url: "https://pathologicalhandwaving.github.io/jekyll-theme-console"
baseurl: "/"
repository: "pathologicalhandwaving/jekyll-theme-console"

header_pages:
  - index.md
  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins_dir:
  - jekyll-paginate
  
